'use client'

import Image from 'next/image'
import styles from './Hero.module.css'

interface HeroProps {
  onContactClick: () => void
}

const highlights = [
  { label: 'Focus', value: 'Product-minded full-stack engineering and AI' },
  { label: 'Strengths', value: 'Reliable shipping, measured experiments, mentorship' },
  { label: 'Now', value: 'Computer Science Student at The City College of New york' },
]

export default function Hero({ onContactClick }: HeroProps) {
  return (
    <section id="landing-page" className={styles.hero}>
      <div className={styles.inner}>
        <div className={styles.copy}>
          <p className={styles.eyebrow}>Mehedi Hasan • Software Engineer</p>
          <h1 className={styles.title}>
            I build thoughtful software experiences that feel handcrafted, not autogenerated.
          </h1>
          <p className={styles.lede}>
            From internal tooling to public-facing platforms, I turn ambiguous ideas into resilient
            products. I care about calm interfaces, fast performance, and the people who rely on the system
            every day.
          </p>
          <div className={styles.actions}>
            <button onClick={onContactClick} className={styles.primaryAction}>
              Work with me
            </button>
            <a href="#projects" className={styles.secondaryAction}>
              View selected work
            </a>
          </div>
          <ul className={styles.highlights}>
            {highlights.map((item) => (
              <li key={item.label}>
                <span>{item.label}</span>
                <p>{item.value}</p>
              </li>
            ))}
          </ul>
        </div>
        <div className={styles.portrait}>
          <div className={styles.photoFrame}>
            <Image
              src="/assets/HeadShot.jpeg"
              alt="Mehedi Hasan"
              width={420}
              height={520}
              priority
            />
          </div>
          <div className={styles.profileCard}>
            <p>Based in New York City</p>
            <p>Shipping reliable software for early-stage teams and established orgs.</p>
            <div className={styles.socials}>
              <a href="https://github.com/techmehedi" target="_blank" rel="noopener noreferrer">
                GitHub
              </a>
              <a href="https://www.linkedin.com/in/techmehedi/" target="_blank" rel="noopener noreferrer">
                LinkedIn
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
